spring:

  config:
    name: gameHaeDuo
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cidgalpxzdu6.us-east-1.rds.amazonaws.com:3306/GameHaeDuo
    username: admin
    password: rpdlago12!


